service: wikipage

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    WIKIPAGE_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
    LOG_PREFIX: "${self:service}"
    STAGE: "${opt:stage, self:provider.stage}"
    SERVICE: "${self:service}"
  tags:
    stage: "${opt:stage, self:provider.stage}"
    service: "${self:service}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  wikipagesSubmit:
    handler: api/wikipages.submit
    memorySize: 128
    description: Store a wikipage to DB.
    events:
      - http:
          path: wikipages
          method: post
          cors: true
  wikipagesList:
    handler: api/wikipages.list
    memorySize: 128
    description: Get all wikipages from DB.
    events:
      - http:
          path: wikipages
          method: get
          cors: true
  wikipagesGet:
    handler: api/wikipages.get
    memorySize: 128
    description: Get a wikipage by id.
    events:
      - http:
          path: wikipages/{id}
          method: get
          cors: true
  wikipagesUpdate:
    handler: api/wikipages.update
    memorySize: 128
    description: Update a wikipage by id.
    events:
      - http:
          path: wikipages/{id}
          method: put
          cors: true
  # wikipagesDelete:
  #   handler: api/wikipages.delete
  #   memorySize: 128
  #   description: Delete a wikipage by id.
  #   events:
  #     - http:
  #         path: wikipages/{id}
  #         method: delete

resources:
  Resources:
    WikipagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.WIKIPAGE_TABLE}