service: wikipage

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    WIKIPAGE_TABLE: "${self:service}-${opt:stage, self:provider.stage}"
    WIKIPAGE_TABLE_INDEX: "${self:provider.environment.WIKIPAGE_TABLE}-pageid-index"
    LOG_PREFIX: "${self:service}"
    STAGE: "${opt:stage, self:provider.stage}"
    SERVICE: "${self:service}"
    STATEMACHINE_ARN: "${self:resources.Outputs.CacheFunc.Value}"
  tags:
    stage: "${opt:stage, self:provider.stage}"
    service: "${self:service}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - "sns:*"
        - "states:StartExecution"
      Resource: "*"

functions:
  # wikipagesSubmit:
  #   handler: api/wikipages.submit
  #   memorySize: 128
  #   description: Store a wikipage to DB.
  #   events:
  #     - http:
  #         path: wikipages
  #         method: post
  #         cors: true
  wikipagesList:
    handler: api/wikipages.list
    memorySize: 128
    description: Get all wikipages from DB.
    events:
      - http:
          path: wikipages
          method: get
          cors: true
  wikipagesGet:
    handler: api/wikipages.get
    memorySize: 128
    description: Get a wikipage by id.
    events:
      - http:
          path: wikipages/{id}
          method: get
          cors: true
  # wikipagesUpdate:
  #   handler: api/wikipages.update
  #   memorySize: 128
  #   description: Update a wikipage by id.
  #   events:
  #     - http:
  #         path: wikipages/{id}
  #         method: put
  #         cors: true
  wikipagesSearchByKeyword:
    handler: api/wikipages.searchbykeyword
    memorySize: 128
    description: Search wikipage by keyword.
    events:
      - http:
          path: wikipages/search/keyword/{word}
          method: get
          cors: true
  # wikipagesSearchByPageid:
  #   handler: api/wikipages.searchbypageid
  #   memorySize: 128
  #   description: Get a wikipage by pageid.
  #   events:
  #     - http:
  #         path: wikipages/search/pageid/{pageid}
  #         method: get
  #         cors: true
  wikipagesCache:
    handler: api/wikipages.cache
    memorySize: 128
    description: Cache a wikipage from SNS cacheWikipage topic
    events:
      - sns: cacheWikipage
  cacheStart:
    handler: api/wikipages.cacheStart
    memorySize: 128
    description: Part of Caching step function
  cacheInfo:
    handler: api/wikipages.cacheInfo
    memorySize: 128
    description: Part of Caching step function
  cacheBacklinks:
    handler: api/wikipages.cacheBacklinks
    memorySize: 128
    description: Part of Caching step function

stepFunctions:
  stateMachines:
    cacheFunction:
      name: cacheFunc
      events:
        - http:
            path: cache
            method: POST
      definition:
        Comment: "Caching logic triggered when a wikipage is first searched"
        StartAt: cacheStart
        States:
          cacheStart:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-cacheStart"
            Next: cacheChoice
          cacheChoice:
            Type: Choice
            Choices:
              - Variable: "$.cache"
                BooleanEquals: false
                Next: cacheEnd
              - Variable: "$.cache"
                BooleanEquals: true
                Next: cacheInfo
            Default: cacheFail
          cacheInfo:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-cacheInfo"
            Next: cacheBacklinks
          cacheBacklinks:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-cacheBacklinks"
            Next: cacheEnd
          cacheEnd:
            Type: Succeed
          cacheFail:
            Type: Fail
            Error: "CacheFailed"
            Cause: "Unknown Error"

resources:
  Resources:
    WikipagesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "pageid"
            AttributeType: "N"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        GlobalSecondaryIndexes:
          - IndexName: ${self:provider.environment.WIKIPAGE_TABLE_INDEX}
            KeySchema:
              - AttributeName: "pageid"
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.WIKIPAGE_TABLE}
  Outputs:
    CacheFunc:
      Description: The ARN of the state machine
      Value:
        Ref: CacheFunc

plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
