service: wikiroam-client

provider:
  name: aws
  stage: dev
  region: us-east-1
  environment:
    CLIENT_BUCKETNAME: "${self:service}-${opt:stage, self:provider.stage}"

plugins:
  - serverless-client-s3

custom:
  client:
    bucketName: ${self:provider.environment.CLIENT_BUCKETNAME}